spring:
    application:
        name: booking-service
    datasource:
        password: password
        url: jdbc:postgresql://localhost:5432/booking
        username: user

    docker:
        compose:
            enabled: false

    flyway:
        create-schemas: true
        schemas: shared

    jackson:
        deserialization:
            accept-empty-array-as-null-object: true
            accept-empty-string-as-null-object: true

    jpa:
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy
        properties:
            hibernate:
                jdbc:
                    time_zone: UTC
        show-sql: false

    rabbitmq:
        host: localhost
        password: password
        port: 5672
        username: user
server:
    port: 8081
