server:
  port: 8083
spring:
  application:
    name: parking-service
  cloud:
    discovery:
      enabled: true
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/parking
    username: user
  flyway:
    create-schemas: true
    schemas: shared
  jackson:
    deserialization:
      accept-empty-array-as-null-object: true
      accept-empty-string-as-null-object: true
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy
    properties:
      hibernate:
        default_schema: shared
        jdbc:
          time_zone: UTC
    show-sql: true
  rabbitmq:
    host: localhost
    password: password
    port: 5672
    username: user
