version: '3'
services:
  postgres:
    image: postgres:14.8-alpine
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  rabbitmq:
    image: rabbitmq:3.12.1-management
    restart: no
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pgdata: